/* Temp table*/
CREATE TABLE #temp_Employee(
EMPLOYID INT,
JOBTITLE VARCHAR(100),
SALARY INT
)
INSERT INTO #temp_Employee
SELECT *
FROM SQLTutorial..EMPLOYSALARIES

 
 DROP TABLE IF EXISTS #temp_Employee2
CREATE TABLE #TEMP_EMPLOYEE2(
JOBTITLE VARCHAR(50),
EMPLOYEESPERJOB INT,
AVGAGE INT,
AVGSALARY INT)

INSERT INTO #TEMP_EMPLOYEE2
SELECT JOBTITLE,COUNT(JOBTITLE),AVG(AGE),AVG(SALARY)
FROM SQLTutorial..EMPLOYEEDEMOGRAPHICS EMP
JOIN SQLTutorial..EMPLOYSALARIES SAL
ON EMP.EMPLOYID = SAL.EMPLOYID
GROUP BY JOBTITLE
