SELECT *
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS

SELECT FIRSTNAME
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS

SELECT FIRSTNAME,LASTNAME
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS

SELECT TOP 5*
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS

SELECT DISTINCT(EMPLOYID)
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS

SELECT DISTINCT(GENDER)
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS

SELECT COUNT(LASTNAME)
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS

SELECT COUNT(FIRSTNAME)
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS

SELECT MAX(SALARY)
FROM SQLTutorial.dbo.EMPLOYSALARIES

SELECT MIN(SALARY)
FROM SQLTutorial.dbo.EMPLOYSALARIES

SELECT AVG(SALARY)
FROM SQLTutorial.dbo.EMPLOYSALARIES
