/* WHERE STATEMENT 
= , <> , < , >,AND, OR ,LIKE ,NULL , NOT NULL , IN
*/

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
--WHERE FIRSTNAME = 'Raja'



SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME <> 'Raja'


SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE <20

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE >30

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME = 'Raja' AND LASTNAME='Afzal' 


SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME = 'Raja' OR LASTNAME='Salman'


SELECT * 
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME LIKE 'S%'


SELECT * 
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME LIKE '%a%'


SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME IS NULL


SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME IS NOT NULL

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME IN ('Raja','HIJAR')
