SELECT GENDER
FROM EMPLOYEEDEMOGRAPHICS
GROUP BY GENDER


SELECT AGE
FROM EMPLOYEEDEMOGRAPHICS
GROUP BY AGE

SELECT GENDER,AGE,COUNT(GENDER) AS COUNTGENDER
FROM EMPLOYEEDEMOGRAPHICS
GROUP BY GENDER,AGE



SELECT GENDER, COUNT(GENDER)
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE > 31
GROUP BY GENDER

SELECT GENDER, COUNT(GENDER) AS COUNTGENDER
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE > 31
GROUP BY GENDER
ORDER BY COUNTGENDER DESC


SELECT *
FROM EMPLOYEEDEMOGRAPHICS
ORDER BY AGE DESC

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
ORDER BY AGE DESC , GENDER DESC


SELECT *
FROM EMPLOYEEDEMOGRAPHICS
ORDER BY 4 DESC, 5 DESC