/* Having satatement should after the group by */
SELECT JOBTITLE,COUNT(JOBTITLE)
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS
JOIN SQLTutorial.dbo.EMPLOYSALARIES
ON EMPLOYEEDEMOGRAPHICS.EMPLOYID = EMPLOYSALARIES.EMPLOYID
GROUP BY JOBTITLE
HAVING COUNT(JOBTITLE) >1